-- =====================================================================
-- GuriUp: Countries / Cities / Districts reference data
-- Source: Firestore 'countries' collection (+ cities/districts subcollections)
-- Safe to re-run: tables use IF NOT EXISTS, rows use ON CONFLICT DO NOTHING
-- =====================================================================

-- 1. TABLES
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS countries (
  id   text PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE IF NOT EXISTS cities (
  id         text PRIMARY KEY,
  name       text NOT NULL,
  country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS districts (
  id      text PRIMARY KEY,
  name    text NOT NULL,
  city_id text NOT NULL REFERENCES cities(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_cities_country_id ON cities(country_id);
CREATE INDEX IF NOT EXISTS idx_districts_city_id ON districts(city_id);

-- 2. DATA
-- ---------------------------------------------------------------------

-- Countries
INSERT INTO countries (id, name) VALUES
  ('djibouti', 'Djibouti'),
  ('ethiopia', 'Ethiopia'),
  ('kenya', 'Kenya'),
  ('rwanda', 'Rwanda'),
  ('somalia', 'Somalia'),
  ('somaliland', 'Somaliland'),
  ('tanzania', 'Tanzania'),
  ('uganda', 'Uganda'),
  ('south_sudan', 'South Sudan'),
  ('burundi', 'Burundi')
ON CONFLICT (id) DO NOTHING;

-- Cities
INSERT INTO cities (id, name, country_id) VALUES
  ('ali_sabieh', 'Ali Sabieh', 'djibouti'),
  ('dikhil', 'Dikhil', 'djibouti'),
  ('djibouti_city', 'Djibouti City', 'djibouti'),
  ('adama', 'Adama', 'ethiopia'),
  ('addis_ababa', 'Addis Ababa', 'ethiopia'),
  ('bahir_dar', 'Bahir Dar', 'ethiopia'),
  ('eldoret', 'Eldoret', 'kenya'),
  ('kisumu', 'Kisumu', 'kenya'),
  ('mombasa', 'Mombasa', 'kenya'),
  ('nairobi', 'Nairobi', 'kenya'),
  ('huye', 'Huye', 'rwanda'),
  ('kigali', 'Kigali', 'rwanda'),
  ('musanze', 'Musanze', 'rwanda'),
  ('rubavu', 'Rubavu', 'rwanda'),
  ('baidoa', 'Baidoa', 'somalia'),
  ('bosaso', 'Bosaso', 'somalia'),
  ('garowe', 'Garowe', 'somalia'),
  ('kismayo', 'Kismayo', 'somalia'),
  ('mogadishu', 'Mogadishu', 'somalia'),
  ('berbera', 'Berbera', 'somaliland'),
  ('borama', 'Borama', 'somaliland'),
  ('burao', 'Burao', 'somaliland'),
  ('hargeisa', 'Hargeisa', 'somaliland'),
  ('arusha', 'Arusha', 'tanzania'),
  ('dar_es_salaam', 'Dar es Salaam', 'tanzania'),
  ('dodoma', 'Dodoma', 'tanzania'),
  ('mwanza', 'Mwanza', 'tanzania'),
  ('entebbe', 'Entebbe', 'uganda'),
  ('jinja', 'Jinja', 'uganda'),
  ('kampala', 'Kampala', 'uganda'),
  ('mbarara', 'Mbarara', 'uganda'),
  ('juba', 'Juba', 'south_sudan'),
  ('wau', 'Wau', 'south_sudan'),
  ('malakal', 'Malakal', 'south_sudan'),
  ('bujumbura', 'Bujumbura', 'burundi'),
  ('gitega', 'Gitega', 'burundi'),
  ('ngozi', 'Ngozi', 'burundi')
ON CONFLICT (id) DO NOTHING;

-- Districts
INSERT INTO districts (id, name, city_id) VALUES
  ('centre', 'Centre', 'ali_sabieh'),
  ('djebel', 'Djebel', 'ali_sabieh'),
  ('guelleh_batal', 'Guelleh Batal', 'ali_sabieh'),
  ('cheik_osman', 'Cheik Osman', 'dikhil'),
  ('palmeraie', 'Palmeraie', 'dikhil'),
  ('ambouli', 'Ambouli', 'djibouti_city'),
  ('balbala', 'Balbala', 'djibouti_city'),
  ('boulaos', 'Boulaos', 'djibouti_city'),
  ('boku', 'Boku', 'adama'),
  ('dabe', 'Dabe', 'adama'),
  ('dembela', 'Dembela', 'adama'),
  ('akaky_kaliti', 'Akaky Kaliti', 'addis_ababa'),
  ('arada', 'Arada', 'addis_ababa'),
  ('bole', 'Bole', 'addis_ababa'),
  ('belay_zeleke', 'Belay Zeleke', 'bahir_dar'),
  ('fasilo', 'Fasilo', 'bahir_dar'),
  ('gish_abay', 'Gish Abay', 'bahir_dar'),
  ('kapseret', 'Kapseret', 'eldoret'),
  ('kesses', 'Kesses', 'eldoret'),
  ('moiben', 'Moiben', 'eldoret'),
  ('kisumu_central', 'Kisumu Central', 'kisumu'),
  ('kisumu_east', 'Kisumu East', 'kisumu'),
  ('kisumu_west', 'Kisumu West', 'kisumu'),
  ('changamwe', 'Changamwe', 'mombasa'),
  ('jomvu', 'Jomvu', 'mombasa'),
  ('kisauni', 'Kisauni', 'mombasa'),
  ('dagoretti', 'Dagoretti', 'nairobi'),
  ('embakasi', 'Embakasi', 'nairobi'),
  ('kamukunji', 'Kamukunji', 'nairobi'),
  ('kasarani', 'Kasarani', 'nairobi'),
  ('kibra', 'Kibra', 'nairobi'),
  ('langata', 'Lang''ata', 'nairobi'),
  ('makadara', 'Makadara', 'nairobi'),
  ('starehe', 'Starehe', 'nairobi'),
  ('westlands', 'Westlands', 'nairobi'),
  ('mbazi', 'Mbazi', 'huye'),
  ('mukura', 'Mukura', 'huye'),
  ('ngoma', 'Ngoma', 'huye'),
  ('tumba', 'Tumba', 'huye'),
  ('gasabo', 'Gasabo', 'kigali'),
  ('kicukiro', 'Kicukiro', 'kigali'),
  ('nyarugenge', 'Nyarugenge', 'kigali'),
  ('cyuve', 'Cyuve', 'musanze'),
  ('gacaca', 'Gacaca', 'musanze'),
  ('kimonyi', 'Kimonyi', 'musanze'),
  ('muhoza', 'Muhoza', 'musanze'),
  ('gisenyi', 'Gisenyi', 'rubavu'),
  ('nyamyumba', 'Nyamyumba', 'rubavu'),
  ('rubavu', 'Rubavu', 'rubavu'),
  ('rugerero', 'Rugerero', 'rubavu'),
  ('berdale', 'Berdale', 'baidoa'),
  ('horseed', 'Horseed', 'baidoa'),
  ('isha', 'Isha', 'baidoa'),
  ('wadaajir', 'Wadaajir', 'baidoa'),
  ('bander_qasim', 'Bander Qasim', 'bosaso'),
  ('biyo_kulule', 'Biyo Kulule', 'bosaso'),
  ('suweyto', 'Suweyto', 'bosaso'),
  ('ufeyn', 'Ufeyn', 'bosaso'),
  ('1-da_luulyo', '1-da Luulyo', 'garowe'),
  ('hanti-wadaag', 'Hanti-wadaag', 'garowe'),
  ('hodhan', 'Hodhan', 'garowe'),
  ('waaberi', 'Waaberi', 'garowe'),
  ('wadajir', 'Wadajir', 'garowe'),
  ('calanley', 'Calanley', 'kismayo'),
  ('fanoole', 'Fanoole', 'kismayo'),
  ('farjano', 'Farjano', 'kismayo'),
  ('shaqalaha', 'Shaqalaha', 'kismayo'),
  ('abdiaziz', 'Abdiaziz', 'mogadishu'),
  ('bondhere', 'Bondhere', 'mogadishu'),
  ('daynile', 'Daynile', 'mogadishu'),
  ('dharkenley', 'Dharkenley', 'mogadishu'),
  ('hamar_jajab', 'Hamar Jajab', 'mogadishu'),
  ('hamar_weyne', 'Hamar Weyne', 'mogadishu'),
  ('hodan', 'Hodan', 'mogadishu'),
  ('howlwadag', 'Howlwadag', 'mogadishu'),
  ('kahda', 'Kahda', 'mogadishu'),
  ('karan', 'Karan', 'mogadishu'),
  ('shangani', 'Shangani', 'mogadishu'),
  ('shibis', 'Shibis', 'mogadishu'),
  ('waberi', 'Waberi', 'mogadishu'),
  ('wadajir_2', 'Wadajir', 'mogadishu'),
  ('wardhigley', 'Wardhigley', 'mogadishu'),
  ('yaqshid', 'Yaqshid', 'mogadishu'),
  ('baraako', 'Baraako', 'berbera'),
  ('darole', 'Darole', 'berbera'),
  ('sabawanag', 'Sabawanag', 'berbera'),
  ('xamar-jajab', 'Xamar-jajab', 'berbera'),
  ('sheekh_cali_jowhar', 'Sheekh Cali Jowhar', 'borama'),
  ('sheekh_cismaan', 'Sheekh Cismaan', 'borama'),
  ('sheekh_makahiil', 'Sheekh Makahiil', 'borama'),
  ('sheekh_salaan', 'Sheekh Salaan', 'borama'),
  ('ali_hussein', 'Ali Hussein', 'burao'),
  ('faro-weyne', 'Faro-weyne', 'burao'),
  ('koodbuur', 'Koodbuur', 'burao'),
  ('october', 'October', 'burao'),
  ('shacabka', 'Shacabka', 'burao'),
  ('26_june', '26 June', 'hargeisa'),
  ('ahmed_dhagax', 'Ahmed Dhagax', 'hargeisa'),
  ('gacan_libaax', 'Gacan Libaax', 'hargeisa'),
  ('ibrahim_koodbuur', 'Ibrahim Koodbuur', 'hargeisa'),
  ('macalin_haruun', 'Macalin Haruun', 'hargeisa'),
  ('mohamoud_haybe', 'Mohamoud Haybe', 'hargeisa'),
  ('arusha_cbd', 'Arusha CBD', 'arusha'),
  ('elerai', 'Elerai', 'arusha'),
  ('kati', 'Kati', 'arusha'),
  ('sombetini', 'Sombetini', 'arusha'),
  ('themi', 'Themi', 'arusha'),
  ('ilala', 'Ilala', 'dar_es_salaam'),
  ('kigamboni', 'Kigamboni', 'dar_es_salaam'),
  ('kinondoni', 'Kinondoni', 'dar_es_salaam'),
  ('temeke', 'Temeke', 'dar_es_salaam'),
  ('ubungo', 'Ubungo', 'dar_es_salaam'),
  ('bahi', 'Bahi', 'dodoma'),
  ('chamwino', 'Chamwino', 'dodoma'),
  ('dodoma_mjini', 'Dodoma Mjini', 'dodoma'),
  ('ilemela', 'Ilemela', 'mwanza'),
  ('nyamagana', 'Nyamagana', 'mwanza'),
  ('division_a', 'Division A', 'entebbe'),
  ('division_b', 'Division B', 'entebbe'),
  ('jinja_central', 'Jinja Central', 'jinja'),
  ('mpumudde-kimaka', 'Mpumudde-Kimaka', 'jinja'),
  ('walukuba-masese', 'Walukuba-Masese', 'jinja'),
  ('central_division', 'Central Division', 'kampala'),
  ('kawempe', 'Kawempe', 'kampala'),
  ('makindye', 'Makindye', 'kampala'),
  ('nakawa', 'Nakawa', 'kampala'),
  ('rubaga', 'Rubaga', 'kampala'),
  ('kakoba', 'Kakoba', 'mbarara'),
  ('kamukuzi', 'Kamukuzi', 'mbarara'),
  ('nyamitanga', 'Nyamitanga', 'mbarara'),
  ('juba_town', 'Juba Town', 'juba'),
  ('kator', 'Kator', 'juba'),
  ('munuki', 'Munuki', 'juba'),
  ('wau_north', 'Wau North', 'wau'),
  ('wau_south', 'Wau South', 'wau'),
  ('malakal_central', 'Malakal Central', 'malakal'),
  ('malakal_north', 'Malakal North', 'malakal'),
  ('muha', 'Muha', 'bujumbura'),
  ('mukaza', 'Mukaza', 'bujumbura'),
  ('ntahangwa', 'Ntahangwa', 'bujumbura'),
  ('gitega_central', 'Gitega Central', 'gitega'),
  ('bugendana', 'Bugendana', 'gitega'),
  ('ngozi_central', 'Ngozi Central', 'ngozi'),
  ('busiga', 'Busiga', 'ngozi')
ON CONFLICT (id) DO NOTHING;